# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\python work\project\main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 600)
        MainWindow.setMinimumSize(QtCore.QSize(440, 600))
        MainWindow.setMaximumSize(QtCore.QSize(440, 600))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setAutoFillBackground(False)
        self.centralWidget.setObjectName("centralWidget")
        self.guitar = QtWidgets.QLabel(self.centralWidget)
        self.guitar.setGeometry(QtCore.QRect(100, 200, 240, 400))
        self.guitar.setText("")
        self.guitar.setPixmap(QtGui.QPixmap("resources/guitar.jpg"))
        self.guitar.setScaledContents(True)
        self.guitar.setObjectName("guitar")
        self.buttonD = QtWidgets.QPushButton(self.centralWidget)
        self.buttonD.setGeometry(QtCore.QRect(10, 210, 80, 80))
        self.buttonD.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/alphabet_d_72px_gray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("resources/alphabet_d_72px.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("resources/alphabet_d_72px_gray.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("resources/alphabet_d_72px.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.buttonD.setIcon(icon)
        self.buttonD.setIconSize(QtCore.QSize(80, 80))
        self.buttonD.setObjectName("buttonD")
        self.buttonG = QtWidgets.QPushButton(self.centralWidget)
        self.buttonG.setGeometry(QtCore.QRect(350, 210, 80, 80))
        self.buttonG.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/alphabet_g_72px_gray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("resources/alphabet_g_72px.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.buttonG.setIcon(icon1)
        self.buttonG.setIconSize(QtCore.QSize(80, 80))
        self.buttonG.setObjectName("buttonG")
        self.buttonE1 = QtWidgets.QPushButton(self.centralWidget)
        self.buttonE1.setGeometry(QtCore.QRect(10, 510, 80, 80))
        self.buttonE1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/alphabet_e_72px_gray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("resources/alphabet_e_72px.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.buttonE1.setIcon(icon2)
        self.buttonE1.setIconSize(QtCore.QSize(80, 80))
        self.buttonE1.setObjectName("buttonE1")
        self.buttonA = QtWidgets.QPushButton(self.centralWidget)
        self.buttonA.setGeometry(QtCore.QRect(10, 360, 80, 80))
        self.buttonA.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/alphabet_a_72px_gray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("resources/alphabet_a_72px.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.buttonA.setIcon(icon3)
        self.buttonA.setIconSize(QtCore.QSize(80, 80))
        self.buttonA.setObjectName("buttonA")
        self.buttonE2 = QtWidgets.QPushButton(self.centralWidget)
        self.buttonE2.setGeometry(QtCore.QRect(350, 510, 80, 80))
        self.buttonE2.setText("")
        self.buttonE2.setIcon(icon2)
        self.buttonE2.setIconSize(QtCore.QSize(80, 80))
        self.buttonE2.setObjectName("buttonE2")
        self.buttonB = QtWidgets.QPushButton(self.centralWidget)
        self.buttonB.setGeometry(QtCore.QRect(350, 370, 80, 80))
        self.buttonB.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/alphabet_b_72px_gray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("resources/alphabet_b_72px.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.buttonB.setIcon(icon4)
        self.buttonB.setIconSize(QtCore.QSize(80, 80))
        self.buttonB.setObjectName("buttonB")
        self.labelA = QtWidgets.QLabel(self.centralWidget)
        self.labelA.setGeometry(QtCore.QRect(157, 358, 30, 30))
        self.labelA.setText("")
        self.labelA.setPixmap(QtGui.QPixmap("resources/alphabet_a_72px.png"))
        self.labelA.setScaledContents(True)
        self.labelA.setObjectName("labelA")
        self.labelB = QtWidgets.QLabel(self.centralWidget)
        self.labelB.setGeometry(QtCore.QRect(253, 358, 30, 30))
        self.labelB.setText("")
        self.labelB.setPixmap(QtGui.QPixmap("resources/alphabet_b_72px.png"))
        self.labelB.setScaledContents(True)
        self.labelB.setObjectName("labelB")
        self.labelD = QtWidgets.QLabel(self.centralWidget)
        self.labelD.setGeometry(QtCore.QRect(157, 285, 30, 30))
        self.labelD.setText("")
        self.labelD.setPixmap(QtGui.QPixmap("resources/alphabet_d_72px.png"))
        self.labelD.setScaledContents(True)
        self.labelD.setObjectName("labelD")
        self.labelE2 = QtWidgets.QLabel(self.centralWidget)
        self.labelE2.setGeometry(QtCore.QRect(253, 432, 30, 30))
        self.labelE2.setText("")
        self.labelE2.setPixmap(QtGui.QPixmap("resources/alphabet_e_72px.png"))
        self.labelE2.setScaledContents(True)
        self.labelE2.setObjectName("labelE2")
        self.labelG = QtWidgets.QLabel(self.centralWidget)
        self.labelG.setGeometry(QtCore.QRect(253, 285, 30, 30))
        self.labelG.setText("")
        self.labelG.setPixmap(QtGui.QPixmap("resources/alphabet_g_72px.png"))
        self.labelG.setScaledContents(True)
        self.labelG.setObjectName("labelG")
        self.labelE1 = QtWidgets.QLabel(self.centralWidget)
        self.labelE1.setGeometry(QtCore.QRect(157, 432, 30, 30))
        self.labelE1.setText("")
        self.labelE1.setPixmap(QtGui.QPixmap("resources/alphabet_e_72px.png"))
        self.labelE1.setScaledContents(True)
        self.labelE1.setObjectName("labelE1")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(210, 0, 20, 180))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralWidget)
        self.lcdNumber.setGeometry(QtCore.QRect(160, 0, 91, 41))
        self.lcdNumber.setDigitCount(4)
        self.lcdNumber.setProperty("intValue", 500)
        self.lcdNumber.setObjectName("lcdNumber")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Guitar Tuner"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

